### ISSUE TITLE
🐛 Bug Report: Entries are not saved! 

### ISSUE THREAD

**Issue by daveit** [appwrite/demo-todo-with-svelte#45]
### 👟 Reproduction steps

Type a ToDo, press Enter nothing happes, the form clears back to the original state!

### 👍 Expected behavior

Display the entered ToDo

### 👎 Actual Behavior

No visual change happens!

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 🧱 Your Environment

N/A

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@daveit thanks for raising this issue! 🙏🏼 If you're experiencing this problem against a local instance of Appwrite, please make sure to add the following permissions for your collection:

![image](https://user-images.githubusercontent.com/1477010/208986819-f538b3d3-025f-4dfd-9f05-da2571d6494e.png)

If you were using the live demo, please try again as I've fixed the permissions now.
